### ISSUE TITLE
Decide on the focus of this new paper

### ISSUE THREAD

**Issue by JJ** [JJ/2019-concurrent-ea-evostar#7]
After the initial proof of concepts, I think this one should focus on scalability and its limits.

* Max number of threads that can be used
* How to balance different types of threads: mixers, reproducers
* How does the number of evaluations and population size per run affect the solution.

Any other thought?

**Comment by juanluck** [comment]
We may consider a sensitivity analysis. Here a gentle introduction:
https://pdfs.semanticscholar.org/cbe2/a4cbcb96ebbfc685d9e16215a1ed4d372532.pdf

**Comment by JJ** [comment]
Thanks!

**Comment by juanluck** [comment]
If we decide to go for a sensitivity analysis (**do we?**), we need to consider the following steps:

1) @JJ : Provide a list with the parameters to be considered in the analysis (we need to fix the rest), including their names (e.g. no_threads) and the minimum and maximum values for each parameter (e.g. min= 1 thread max=1000 threads). Additionally, what is/are the result/s that we aim to analyze?  number of evaluations to solution? time to solution? success rate?
2) @juanluck : Based on 1), I will provide a csv file with the design of experiments (DoE), i.e. all the combination of parameters to be tested (get ready for some thousands of runs).
3) @JJ : For each setting (i.e. combination of parameter), provide the result (in a csv file?) as the average of some independent runs. 
NOTE: In https://pdfs.semanticscholar.org/cbe2/a4cbcb96ebbfc685d9e16215a1ed4d372532.pdf, they only use 4 runs which is not much. The issue here is the massive amount of computation that we need to face.
4) @juanluck : Based on 3), I will carry out the sensitivity analysis and produce the graphs to be analyzed.

If you are interested, you can see further details in:
https://cran.r-project.org/web/packages/pse/vignettes/pse_tutorial.pdf
https://cran.r-project.org/web/packages/sensitivity/sensitivity.pdf
https://www.rdocumentation.org/packages/sensitivity/versions/1.15.2/topics/fast99

**Comment by JJ** [comment]
Gotcha!
